name: DotNet- Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Echo token URL for EInvoicing (Okta)
        run: |
          set -euo pipefail
          BASE_URL="${{ secrets.OKTA_ACCESS_TOKEN_URL }}"
          if [[ -z "${BASE_URL}" ]]; then
            echo "OKTA_ACCESS_TOKEN_URL secret is empty"
            exit 0
          fi

          if [[ "${BASE_URL}" =~ /connect/token$ ]]; then
            TOKEN_URL="${BASE_URL}"
          else
            TOKEN_URL="${BASE_URL%/}/connect/token"
          fi

          echo "Okta token URL: ${TOKEN_URL}"

      - name: Echo token URL for A1099 (AI)
        run: |
          set -euo pipefail
          BASE_URL="${{ secrets.AI_SBX_URL }}"
          if [[ -z "${BASE_URL}" ]]; then
            echo "AI_SBX_URL secret is empty"
            exit 0
          fi

          if [[ "${BASE_URL}" =~ /connect/token$ ]]; then
            TOKEN_URL="${BASE_URL}"
          else
            TOKEN_URL="${BASE_URL%/}/connect/token"
          fi

          echo "A1099 token URL: ${TOKEN_URL}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Package
        run: dotnet build --no-restore --configuration Release
      - name: Test cases with EInvoicing only for now
        run: dotnet test --verbosity normal --configuration Release
        env:
          BEARER_TOKEN_EINVOICING: ${{ env.BEARER_TOKEN_EINVOICING }}
          BEARER_TOKEN_A1099: ${{ env.BEARER_TOKEN_A1099 }}
