name: DotNet- Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Retrieve bearer token for E-Invoicing
        id: get_bearer_token_e_invoicing
        run: |
          response=$(curl -X POST ${{secrets.OKTA_ACCESS_TOKEN_URL}}/connect/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{secrets.OKTA_CLIENT_ID}}&client_secret=${{secrets.OKTA_CLIENT_SECRET}}")
          token=$(echo $response | jq -r '.access_token')
          echo "BEARER_TOKEN_EINVOICING=${token}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
      - name: Retrieve bearer token for Track1099
        id: get_bearer_token_track1099
        run: |
          response=$(curl -X POST https://identity.qa.avalara.io/connect/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{secrets.AI_CLIENT_ID}}&client_secret=${{secrets.AI_CLIENT_SECRET}}")
          token=$(echo $response | jq -r '.access_token')
          echo "BEARER_TOKEN_TRACK1099=${token}" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.x.x
            2.2.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Package
        run: dotnet build --no-restore --configuration Release
      - name: Test cases
        run: dotnet test --verbosity normal --configuration Release
